/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CartonController;
import controller.JuegoController;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.carton.Carton;
import view.FrmCarton;

/**
 *
 * @author joans
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    private String tipoJuego;
    private String modo;
    private int cantidadCartones;

    private PanelCarton panelCarton;
    private PanelTablero panelTablero;
    private PanelTombola panelTombola;
    private PanelResultados panelResultados;

    private JuegoController juegoController;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);

        panelTablero = new view.PanelTablero();
        panelTombola = new view.PanelTombola();
        panelResultados = new view.PanelResultados();

        pnlTablero.add(panelTablero, java.awt.BorderLayout.CENTER);
        pnTombola.add(panelTombola, java.awt.BorderLayout.CENTER);

    }

    private void iniciarJuegoSegunModo() {

        CartonController controller = new CartonController();
        java.util.List<Carton> lista = new java.util.ArrayList<>();

        if ("AUTOMATICO".equals(modo)) {

            for (int i = 1; i <= cantidadCartones; i++) {
                Carton c = controller.generarCartonAutomatico("J" + i);
                lista.add(c);

                FrmCarton ventana = new FrmCarton();
                ventana.recibirCarton(c);
                ventana.setVisible(true);
            }

            juegoController.iniciarJuego(model.juego.TipoJuego.valueOf(tipoJuego), lista);
           panelTombola.setJuegoController(juegoController, false);

        } else {

            for (int i = 1; i <= cantidadCartones; i++) {

                JOptionPane.showMessageDialog(
                        this,
                        "Llenando cartón #" + i,
                        "Cartón Manual",
                        JOptionPane.INFORMATION_MESSAGE
                );

                int[][] numeros = llenarCartonManual();
                Carton c = controller.generarCartonManual("MANUAL_" + i, numeros);
                lista.add(c);

                FrmCarton ventana = new FrmCarton();
                ventana.recibirCarton(c);
                ventana.setVisible(true);
            }

            juegoController.iniciarJuego(model.juego.TipoJuego.valueOf(tipoJuego), lista);
             panelTombola.setJuegoController(juegoController, true);
        }
    }

    public void enviarModo(String tipoJuego, String modo, int cantidadCartones) {

        this.tipoJuego = tipoJuego;
        this.modo = modo;
        this.cantidadCartones = cantidadCartones;

        juegoController = new controller.JuegoController(panelTablero, panelTombola, panelResultados);

        iniciarJuegoSegunModo();
        pnlResultados.add(panelResultados, java.awt.BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLlenarCarton = new javax.swing.JTable();
        pnlResultados = new javax.swing.JPanel();
        pnTombola = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlTablero = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnCarton = new javax.swing.JMenuItem();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        tbLlenarCarton.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ));
        jScrollPane1.setViewportView(tbLlenarCarton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlResultados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlResultados.setMaximumSize(new java.awt.Dimension(225, 96));
        pnlResultados.setMinimumSize(new java.awt.Dimension(225, 96));
        pnlResultados.setPreferredSize(new java.awt.Dimension(225, 96));
        pnlResultados.setLayout(new java.awt.BorderLayout());

        pnTombola.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnTombola.setMaximumSize(new java.awt.Dimension(250, 478));
        pnTombola.setMinimumSize(new java.awt.Dimension(250, 478));
        pnTombola.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOMBOLA");
        pnTombola.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());
        pnTombola.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pnlTablero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTablero.setLayout(new java.awt.BorderLayout());

        jMenu1.setText("Inicio");
        jMenu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu1KeyPressed(evt);
            }
        });

        jMenuItem1.setText("Reiniciar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Agregar");

        mnCarton.setText("Cartón");
        mnCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCartonActionPerformed(evt);
            }
        });
        jMenu2.add(mnCarton);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnTombola, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addComponent(pnlTablero, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(pnTombola, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu1KeyPressed

    }//GEN-LAST:event_jMenu1KeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        juegoController.reiniciar();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCartonActionPerformed

        if (juegoController == null) {
            JOptionPane.showMessageDialog(this,
                    "Debes iniciar un juego antes de agregar cartones.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String[] opciones = {"Automático", "Manual", "Cancelar"};

        int opcion = JOptionPane.showOptionDialog(
                this,
                "¿Cómo desea generar el nuevo cartón?",
                "Nuevo Cartón",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]
        );

        if (opcion == 2 || opcion == JOptionPane.CLOSED_OPTION) {
            return;
        }

        CartonController controller = new CartonController();
        Carton cartonNuevo;

        if (opcion == 0) {

            String nombre = "EXTRA_" + (int) (Math.random() * 99);
            cartonNuevo = controller.generarCartonAutomatico(nombre);

            JOptionPane.showMessageDialog(this,
                    "Cartón automático generado correctamente.");
        } else {

            JOptionPane.showMessageDialog(this,
                    "Llenará un nuevo cartón manualmente.");

            int[][] valores = llenarCartonManual();

            String nombre = "MANUAL_EXTRA_" + (int) (Math.random() * 9999);
            cartonNuevo = controller.generarCartonManual(nombre, valores);

            JOptionPane.showMessageDialog(this,
                    "Cartón manual creado correctamente.");
        }

        FrmCarton ventana = new FrmCarton();
        ventana.recibirCarton(cartonNuevo);
        ventana.setVisible(true);

        juegoController.agregarCarton(cartonNuevo);

        JOptionPane.showMessageDialog(this,
                "Cartón agregado al juego satisfactoriamente.");


    }//GEN-LAST:event_mnCartonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    private int[][] llenarCartonManual() {

        limpiarTablaCarton();

        jDialog1.setModal(true);
        jDialog1.setSize(618, 471);
        jDialog1.setLocationRelativeTo(this);
        jDialog1.setVisible(true);
        int[][] matriz = new int[5][5];

        for (int fila = 0; fila < 5; fila++) {
            for (int col = 0; col < 5; col++) {

                if (fila == 2 && col == 2) {
                    tbLlenarCarton.setValueAt("LIBRE", fila, col);
                    matriz[fila][col] = 0;
                    continue;
                }

                boolean valido = false;
                int numero = 0;

                while (!valido) {
                    String input = javax.swing.JOptionPane.showInputDialog(
                            this,
                            "Ingrese número para [" + fila + "," + col + "]\nColumna "
                            + getColumnaLetra(col) + "\nRango permitido: "
                            + obtenerRangoColumna(col),
                            "Ingresar número",
                            javax.swing.JOptionPane.QUESTION_MESSAGE
                    );

                    if (input == null) {

                        jDialog1.setVisible(true);

                        JOptionPane.showMessageDialog(
                                this,
                                "Debe ingresar un número.\nPuede revisar el cartón en la tabla.",
                                "Aviso",
                                JOptionPane.INFORMATION_MESSAGE
                        );

                        continue;
                    }

                    try {
                        numero = Integer.parseInt(input);

                        int min = obtenerMin(col);
                        int max = obtenerMax(col);

                        if (numero < min || numero > max) {
                            javax.swing.JOptionPane.showMessageDialog(this,
                                    "Número fuera de rango.\nDebe estar entre " + min + " y " + max,
                                    "Error",
                                    javax.swing.JOptionPane.ERROR_MESSAGE);
                            continue;
                        }

                        if (existeEnMatriz(matriz, numero)) {
                            javax.swing.JOptionPane.showMessageDialog(this,
                                    "Este número ya fue usado.",
                                    "Repetido",
                                    javax.swing.JOptionPane.ERROR_MESSAGE);
                            continue;
                        }

                        valido = true;

                    } catch (NumberFormatException e) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                                "Debe ingresar un número válido.",
                                "Error",
                                javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                }

                matriz[fila][col] = numero;
                tbLlenarCarton.setValueAt(numero, fila, col);
            }
        }

        return matriz;
    }

    private boolean existeEnMatriz(int[][] m, int valor) {
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                if (m[i][j] == valor) {
                    return true;
                }
            }
        }
        return false;
    }

    private void limpiarTablaCarton() {
        for (int fila = 0; fila < 5; fila++) {
            for (int col = 0; col < 5; col++) {
                tbLlenarCarton.setValueAt(null, fila, col);
            }
        }
    }

    private String getColumnaLetra(int col) {
        return switch (col) {
            case 0 ->
                "B (1-15)";
            case 1 ->
                "I (16-30)";
            case 2 ->
                "N (31-45)";
            case 3 ->
                "G (46-60)";
            case 4 ->
                "O (61-75)";
            default ->
                "";
        };
    }

    private String obtenerRangoColumna(int col) {
        return switch (col) {
            case 0 ->
                "1 - 15";
            case 1 ->
                "16 - 30";
            case 2 ->
                "31 - 45";
            case 3 ->
                "46 - 60";
            case 4 ->
                "61 - 75";
            default ->
                "";
        };
    }

    private int obtenerMin(int col) {
        return new int[]{1, 16, 31, 46, 61}[col];
    }

    private int obtenerMax(int col) {
        return new int[]{15, 30, 45, 60, 75}[col];
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnCarton;
    private javax.swing.JPanel pnTombola;
    private javax.swing.JPanel pnlResultados;
    private javax.swing.JPanel pnlTablero;
    private javax.swing.JTable tbLlenarCarton;
    // End of variables declaration//GEN-END:variables
}
