/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JLabel;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.carton.Carton;

/**
 *
 * @author joans
 */
public class PanelCarton extends javax.swing.JPanel {

    private JLabel[][] celdas = new JLabel[5][5];

    /**
     * Creates new form PanelCarton
     */
    public PanelCarton() {
        initComponents();
        setLayout(new GridLayout(5, 5, 5, 5));
        setBackground(Color.black);

        crearCuadricula();
    }

    // ============================================
    //     CREAR TABLA VACÍA (5x5)
    // ============================================
    private void crearCuadricula() {
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {

                JLabel lbl = new JLabel("", JLabel.CENTER);
                lbl.setOpaque(true);
                lbl.setBackground(new Color(230, 230, 230));
                lbl.setFont(new Font("Arial", Font.BOLD, 20));
                lbl.setBorder(BorderFactory.createLineBorder(Color.BLACK));

                celdas[i][j] = lbl;
                add(lbl);
            }
        }
    }

    // ============================================
    //     MOSTRAR UN CARTÓN
    // ============================================
    public void mostrarCarton(Carton carton) {
        int[][] nums = carton.getNumeros();
        boolean[][] marcados = carton.getMarcados();

        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {

                JLabel lbl = celdas[i][j];

                if (i == 2 && j == 2) {
                    lbl.setText("Libre");
                    lbl.setBackground(new Color(150, 255, 150));
                    continue;
                }

                lbl.setText(String.valueOf(nums[i][j]));

                if (marcados[i][j]) {
                    lbl.setBackground(new Color(120, 200, 255));
                } else {
                    lbl.setBackground(new Color(230, 230, 230));
                }
            }
        }

        repaint();
        revalidate();
    }

    // ============================================
    //     LIMPIAR CARTÓN
    // ============================================
   public void limpiar() {
    for (int i = 0; i < 5; i++) {
        for (int j = 0; j < 5; j++) {
            JLabel lbl = celdas[i][j];

            if (i == 2 && j == 2) {
                lbl.setText("Libre");
                lbl.setBackground(new Color(150, 255, 150)); // Color verde para la casilla libre
            } else {
               
                lbl.setBackground(new Color(230, 230, 230)); // Color normal
            }
        }
    }
    repaint();
    revalidate();
}
    

public boolean marcarNumero(int numero, Carton carton) {
    int[][] nums = carton.getNumeros();
    boolean[][] marcados = carton.getMarcados();
    boolean encontrado = false;

    for (int i = 0; i < 5; i++) {
        for (int j = 0; j < 5; j++) {

         
            if (i == 2 && j == 2) continue;

            if (nums[i][j] == numero) {
                marcados[i][j] = true;        
                celdas[i][j].setBackground(new Color(120, 200, 255)); 
                encontrado = true;
            }
        }
    }

    repaint();
    revalidate();
    return encontrado;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
