/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Gipsy
 */
public class FrmModoJuego extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmModoJuego.class.getName());

    /**
     * Creates new form FrmModoJuego
     */
    public FrmModoJuego() {
        initComponents();
        
        buttonGroup1.add(rbNormal);
        buttonGroup1.add(rbCuatroEsquinas);
        buttonGroup1.add(rbCartonLleno);
        
        
            buttonGroup2.add(rbAutomatico);
        buttonGroup2.add(rbManual);
        
        jButton1.addActionListener(evt -> {
    if (rbNormal.isSelected()) {
        System.out.println("Modo seleccionado: NORMAL");
    } else if (rbCuatroEsquinas.isSelected()) {
        System.out.println("Modo seleccionado: CUATRO_ESQUINAS");
    } else if (rbCartonLleno.isSelected()) {
        System.out.println("Modo seleccionado: CARTON_LLENO");
    } else {
        System.out.println("Debe seleccionar un modo.");
    }
});


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbNormal = new javax.swing.JRadioButton();
        rbCartonLleno = new javax.swing.JRadioButton();
        rbCuatroEsquinas = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        rbAutomatico = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbManual = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(620, 552));
        jPanel1.setMinimumSize(new java.awt.Dimension(620, 552));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Seleccione el TIPO de juego");

        rbNormal.setText("NORMAL");

        rbCartonLleno.setText("Carton Lleno");

        rbCuatroEsquinas.setText("Cuatro Esquinas");

        jButton1.setText("SIGUIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rbAutomatico.setText("Automatico");
        rbAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAutomaticoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Seleccione el MODO de juego");

        rbManual.setText("Manual");
        rbManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbManualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbCuatroEsquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbCartonLleno, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(rbAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbManual, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(rbNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCuatroEsquinas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCartonLleno)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbAutomatico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbManual)
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAutomaticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAutomaticoActionPerformed

    private void rbManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbManualActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
    // VALIDAR TIPO DE JUEGO
    String tipoJuego = null;

    if (rbNormal.isSelected()) {
        tipoJuego = "NORMAL";
    } else if (rbCuatroEsquinas.isSelected()) {
        tipoJuego = "CUATRO_ESQUINAS";
    } else if (rbCartonLleno.isSelected()) {
        tipoJuego = "CARTON_LLENO";
    }

    if (tipoJuego == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Debe seleccionar un TIPO de juego.",
                "Advertencia",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // VALIDAR MODO DE JUEGO
    String modo = null;

    if (rbAutomatico.isSelected()) {
        modo = "AUTOMATICO";
    } else if (rbManual.isSelected()) {
        modo = "MANUAL";
    }

    if (modo == null) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Debe seleccionar un MODO de juego.",
                "Advertencia",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

 
    String input = javax.swing.JOptionPane.showInputDialog(
            this,
            "Ingrese la cantidad de cartones:",
            "Cantidad de Cartones",
            javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    if (input == null || input.trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Debe ingresar una cantidad válida.",
                "Advertencia",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int cantidadCartones;

    try {
        cantidadCartones = Integer.parseInt(input);

        if (cantidadCartones <= 0) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "La cantidad debe ser mayor a 0.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese un número válido.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    
    System.out.println("Tipo Juego: " + tipoJuego);
    System.out.println("Modo: " + modo);
    System.out.println("Cartones: " + cantidadCartones);

    
    FrmPrincipal siguiente = new FrmPrincipal();
    siguiente.enviarModo(tipoJuego, modo, cantidadCartones);
   
    siguiente.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmModoJuego().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbAutomatico;
    private javax.swing.JRadioButton rbCartonLleno;
    private javax.swing.JRadioButton rbCuatroEsquinas;
    private javax.swing.JRadioButton rbManual;
    private javax.swing.JRadioButton rbNormal;
    // End of variables declaration//GEN-END:variables
}
