/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import model.juego.TableroNumeros;

/**
 *
 * @author joans
 */
public class PanelTablero extends javax.swing.JPanel {

    
    private JLabel[] numerosLabels = new JLabel[75];
    /**
     * Creates new form PanelTablero
     */
    public PanelTablero() {
        initComponents();
        setLayout(new java.awt.GridLayout(15, 5, 2, 2)); 
        inicializarTablero();
    }
    
   private void inicializarTablero() {
    for (int i = 0; i < 75; i++) {
        JLabel lbl = new JLabel(String.valueOf(i + 1), JLabel.CENTER);
        lbl.setOpaque(true);
        lbl.setBackground(new Color(230, 230, 230));
        lbl.setFont(new Font("Arial", Font.BOLD, 12));
        lbl.setBorder(BorderFactory.createLineBorder(Color.BLACK));

        numerosLabels[i] = lbl;
        add(lbl);
    }
    
     repaint();
        revalidate();
}

     
      // Método para actualizar tablero según números salidos
    public void actualizarTablero(TableroNumeros tablero) {
        boolean[] numerosSalidos = tablero.getNumerosSalidos(); 
        for (int i = 0; i < 75; i++) {
            if (numerosSalidos[i]) {
                numerosLabels[i].setBackground(new Color(120, 200, 255));
            } else {
                numerosLabels[i].setBackground(new Color(230, 230, 230)); 
            }
        }
        repaint();
        revalidate();
    }

   
    public void limpiar() {
        for (int i = 0; i < 75; i++) {
            numerosLabels[i].setBackground(new Color(230, 230, 230));
        }
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
