/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.JuegoControlador;
import javax.swing.JOptionPane;

/**
 *
 * @author joans
 */
public class PanelTombola extends javax.swing.JPanel {
    



    /**
     * Creates new form PanelTombola
     */
    public PanelTombola() {
        initComponents();
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnSacarBola = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tombola.gif"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        lblNumero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(51, 51, 51));
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setText("SALIO EL");
        lblNumero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblResultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 51, 102));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("SALIO EL");
        lblResultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSacarBola.setText("MOVER TOMBOLA");
        btnSacarBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarBolaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumero))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnSacarBola)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnSacarBola)
                .addGap(45, 45, 45))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacarBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarBolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSacarBolaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacarBola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
public void mostrarNumero(String numero) {
        lblNumero.setText(numero);
    }

  public void setJuegoController(JuegoControlador controller, boolean esManual) {
    btnSacarBola.addActionListener(e -> {
        if (esManual) {
            // Pedir número al usuario
            String input = javax.swing.JOptionPane.showInputDialog(
                    this,
                    "Ingrese un número de 1 a 75 que aún no haya salido",
                    "Número Manual",
                    javax.swing.JOptionPane.QUESTION_MESSAGE
            );

            if (input != null) {
                try {
                    int numero = Integer.parseInt(input);
                    if (controller.getTombola().yaSalio(numero)) {
                        JOptionPane.showMessageDialog(this,
                                "Este número ya salió",
                                "Error",
                                JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    controller.agregarNumero(numero);

                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this,
                            "Debe ingresar un número válido",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                } catch (IllegalArgumentException | IllegalStateException ex) {
                    JOptionPane.showMessageDialog(this,
                            ex.getMessage(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }

        } else {
            // Modo automático
            controller.sacarNumero();
        }
    });
}


}
